# Hiera Learning VM
#
Vagrant.configure("2") do |config|

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end

  config.vm.define :single do |single|
    single.vm.box = "centos6"
    single.vm.hostname = "single01.forkedprocess.com"
    single.vm.network :private_network, ip: "192.168.33.50"
    single.vm.network "forwarded_port", guest: 80, host: 8080
  end

end
