# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Puppet environment for Master/Agent testing
#
# NOTE:
# With the vagrant-hosts plugin, you have to provision AFTER the environment
# is booted:
# vagrant up --provider=vmware_fusion --no-provision
# vagrant provision
#
require 'vagrant-hosts'

INSTANCES=2
DOMAIN="example.com"
SUBNET="192.168.33"

Vagrant.configure("2") do |config|

  # Puppet master
  config.vm.define :master do |master|
    master.vm.box = "centos64"
    master.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box"
    master.vm.hostname = "puppet.#{DOMAIN}"
    master.vm.network :private_network, ip: "#{SUBNET}.10"
    master.vm.network :forwarded_port, guest: 80, host: 8080
    master.vm.provision :shell, :path => "provision-centos.sh"
    master.vm.provision :hosts
  end

  # Puppet nodes
  INSTANCES.times do |i|
    config.vm.define "node#{i}".to_sym do |node|
      node.vm.box = "centos64"
      node.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503-nocm.box"
      node.vm.hostname = "node%d.#{DOMAIN}" % i
      node.vm.network :private_network, ip: "#{SUBNET}.%d" % (10 + i + 1)
      #node.vm.network :forwarded_port, guest: 80, host: 9090
      node.vm.provision :shell, :path => "provision-centos.sh"
      node.vm.provision :hosts
    end
  end

end
